### ISSUE TITLE
problem with addition of disorders to a task page

### ISSUE THREAD

**Issue by poldrack** [poldracklab/cogat#112]
I tried adding a disorder to one of the task pages, but after the addition is done the disorder still doesn't show up under the task page

**Comment by poldrack** [comment]
seems like potentially a bigger issue - same happens when I try to add a contrast to an existing concept that is listed for a task - it lets me specify it, but then it doesn't actually show up in the list, as if it's not being saved

**Comment by rwblair** [comment]
Fixed for task present. Concept issue fixed with updated way of directly relating contrasts to concepts.
