### ISSUE TITLE
Typo on Concept, Disorder, Trait, and Behavior pages.

### ISSUE THREAD

**Issue by tsalo** [poldracklab/cogat#121]
Neurosynth is misspelled as Neruosynth at the following locations:
- https://github.com/poldracklab/cogat/blob/master/cognitive/apps/atlas/templates/atlas/view_behavior.html#L36
- https://github.com/poldracklab/cogat/blob/master/cognitive/apps/atlas/templates/atlas/view_trait.html#L36
- https://github.com/poldracklab/cogat/blob/master/cognitive/apps/atlas/templates/atlas/view_disorder.html#L35
- https://github.com/poldracklab/cogat/blob/master/cognitive/apps/atlas/templates/atlas/view_concept.html#L92

**Comment by rwblair** [comment]
Should  be updated, thank you for the issue
