### ISSUE TITLE
cognitiveatlas.org doesn't work

### ISSUE THREAD

**Issue by yanapanikratova** [poldracklab/cogat#147]
Hello!

There is an "Internal Server Error" at cognitiveatlas.org. I had a message there to make an issue at github. Please help.

Yana

**Comment by poldrack** [comment]
thanks for letting us know - we are working on it and will report once the issue is fixed

**Comment by yanapanikratova** [comment]
Thank you, it works now! 

But I have a new problem, please help if you can. I have uploaded an fMRI group activation map to [neurovault.org](http://neurovault.org/) and had to choose a Cognitive Atlas Paradigm from the list. My task was absent in this list, so I have added it to [cognitiveatlas.org](http://cognitiveatlas.org/) ([Cognitive Atlas](http://www.cognitiveatlas.org/task/id/tsk_ORAzdOO86kNfM/)). However, when I try to choose this task at [neurovault.org](http://neurovault.org/) when describing metadata of the map, my task is absent there again. Couldn’t you help? What should I do next?

**Comment by yanapanikratova** [comment]
Dear Dr. Poldrack, sorry for the disturbance. The neurovault team helped to solve the problem.

Thank you, 
Yana
