### ISSUE TITLE
Character rendering problem with Penn Word Memory Test

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/cogat#73]
![image](https://user-images.githubusercontent.com/238759/29148230-ebabe77c-7d20-11e7-8f42-cf183b48dd5a.png)

**Comment by rwblair** [comment]
The 'â' character is showing up in the old database dumps. Still need to fix this at the import level.

From the old site api looks like a unicode apostrophe:
http://cognitiveatlas.org/api/v-alpha/task?id=trm_56a2a665baeb1
