### ISSUE TITLE
Task definitions appear in tooltips but not in task descriptions

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/cogat#74]
![image](https://user-images.githubusercontent.com/238759/29148263-1d3356d6-7d21-11e7-86ac-be0b93f41a7b.png)

![image](https://user-images.githubusercontent.com/238759/29148267-2bab1b54-7d21-11e7-8d84-d5c8291f5c5e.png)

**Comment by poldrack** [comment]
you beat me to it! same for concepts

**Comment by rwblair** [comment]
Fixed in #80

**Comment by poldrack** [comment]
this does not seem to have fixed the problem...

**Comment by rwblair** [comment]
Sorry haven't won't close until the code is deployed to the server.
