### ISSUE TITLE
results from popup on search are wonky

### ISSUE THREAD

**Issue by poldrack** [poldracklab/cogat#94]
when I type somethign into the search window, the results initially seem good but then get replaced with stuff that seems unrelated, see attached image
![image](https://user-images.githubusercontent.com/871056/30569677-135b9b20-9c91-11e7-86d4-e38c1d03a516.png)

**Comment by rwblair** [comment]
Strange, working for me in Chrome, will have to try it out in more browsers/OS to try and reproduce:

<img width="1306" alt="screen shot 2017-09-19 at 10 34 35 am" src="https://user-images.githubusercontent.com/14927911/30618036-9c420124-9d4d-11e7-9b6e-7d1a3ad51589.png">
